// <auto-generated />
using System;
using MediaLendingService.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaLendingService.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240705004251_SeedBooks")]
    partial class SeedBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediaLendingService.Server.Entities.BookEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCheckedOut")
                        .HasColumnType("bit");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PublicationDate")
                        .HasColumnType("date");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.HasIndex("PublicationDate");

                    b.HasIndex("Title");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Johnnie Schmeler",
                            CategoryId = 8,
                            CoverImage = "https://picsum.photos/640/480/?image=668",
                            Description = "Id quaerat quas incidunt. Numquam voluptatem dolores quod adipisci rerum. Ea aut non ea impedit culpa dolorum minus placeat. Dolore nobis non sint atque magnam. Alias atque ducimus corrupti quo qui enim veniam quidem. Quis at quia at facilis.",
                            IsCheckedOut = false,
                            Isbn = "0910430808773",
                            PageCount = 428,
                            PublicationDate = new DateOnly(2019, 2, 19),
                            Publisher = "Kunze - Bartell",
                            Title = "Et quasi est."
                        },
                        new
                        {
                            Id = 2,
                            Author = "Luther O'Hara",
                            CategoryId = 7,
                            CoverImage = "https://picsum.photos/640/480/?image=72",
                            Description = "Quasi quis magnam. Sunt perspiciatis animi quasi assumenda voluptatem blanditiis porro inventore recusandae. Enim reprehenderit exercitationem aut aliquam laudantium et. Rerum dicta vel fugit recusandae dolor.",
                            IsCheckedOut = true,
                            Isbn = "9287472820386",
                            PageCount = 242,
                            PublicationDate = new DateOnly(2014, 7, 23),
                            Publisher = "Hodkiewicz, Gottlieb and Nicolas",
                            Title = "Quo odio autem."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Abigail Moore",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=9",
                            Description = "Laborum autem omnis et libero saepe cumque ipsum beatae. Nihil earum voluptates nisi quia ducimus. Voluptas quo commodi in commodi. Molestias enim omnis.",
                            IsCheckedOut = false,
                            Isbn = "5734037856167",
                            PageCount = 893,
                            PublicationDate = new DateOnly(2021, 10, 11),
                            Publisher = "Kunze Group",
                            Title = "Voluptatibus ex ut."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Susie Fahey",
                            CategoryId = 7,
                            CoverImage = "https://picsum.photos/640/480/?image=102",
                            Description = "Sunt veniam dolore omnis aliquam sed saepe rerum et cum. Dolorem in ea quia. Possimus commodi hic.",
                            IsCheckedOut = true,
                            Isbn = "4512561145060",
                            PageCount = 849,
                            PublicationDate = new DateOnly(2020, 4, 29),
                            Publisher = "Schumm, Tromp and Cummerata",
                            Title = "Magnam qui aut."
                        },
                        new
                        {
                            Id = 5,
                            Author = "Abbie Will",
                            CategoryId = 8,
                            CoverImage = "https://picsum.photos/640/480/?image=298",
                            Description = "Praesentium consequuntur autem ab perspiciatis ad. Eaque ad eum. Nisi et tempore. Cumque laboriosam dicta et illo.",
                            IsCheckedOut = true,
                            Isbn = "2888291933201",
                            PageCount = 402,
                            PublicationDate = new DateOnly(2019, 3, 14),
                            Publisher = "Mueller, Wintheiser and Bradtke",
                            Title = "At ut non."
                        },
                        new
                        {
                            Id = 6,
                            Author = "Willy Hahn",
                            CategoryId = 2,
                            CoverImage = "https://picsum.photos/640/480/?image=331",
                            Description = "Corrupti enim officia repudiandae voluptas reprehenderit quia. Quas dolorem hic perferendis sunt eum voluptatem. Corrupti officiis autem atque nobis delectus.",
                            IsCheckedOut = true,
                            Isbn = "7597317629855",
                            PageCount = 946,
                            PublicationDate = new DateOnly(2024, 5, 7),
                            Publisher = "Bauch and Sons",
                            Title = "Dicta ipsum fugit."
                        },
                        new
                        {
                            Id = 7,
                            Author = "Alexane Ruecker",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=588",
                            Description = "Dolor et aut itaque quisquam saepe occaecati delectus voluptatum officiis. Autem sit quisquam. Voluptas neque nobis dignissimos architecto provident explicabo quas doloribus et.",
                            IsCheckedOut = false,
                            Isbn = "5820888622683",
                            PageCount = 197,
                            PublicationDate = new DateOnly(2016, 2, 29),
                            Publisher = "Bernhard LLC",
                            Title = "Eveniet similique minima."
                        },
                        new
                        {
                            Id = 8,
                            Author = "Stewart Reilly",
                            CategoryId = 3,
                            CoverImage = "https://picsum.photos/640/480/?image=776",
                            Description = "Voluptatem eos ea est quia. Eos dolor eligendi. Tempora rerum et et sunt omnis.",
                            IsCheckedOut = false,
                            Isbn = "8823166410764",
                            PageCount = 293,
                            PublicationDate = new DateOnly(2023, 9, 15),
                            Publisher = "Wisozk and Sons",
                            Title = "Velit et voluptas."
                        },
                        new
                        {
                            Id = 9,
                            Author = "Nicholaus Ratke",
                            CategoryId = 7,
                            CoverImage = "https://picsum.photos/640/480/?image=432",
                            Description = "Repellendus nihil dolor et aliquid fuga nesciunt. Temporibus facere aut. Odit exercitationem occaecati velit est. Sed natus quaerat veniam numquam molestiae quia veniam et voluptates.",
                            IsCheckedOut = true,
                            Isbn = "0401794332931",
                            PageCount = 197,
                            PublicationDate = new DateOnly(2017, 12, 22),
                            Publisher = "Emmerich - Metz",
                            Title = "At ipsam possimus."
                        },
                        new
                        {
                            Id = 10,
                            Author = "Oliver Daugherty",
                            CategoryId = 3,
                            CoverImage = "https://picsum.photos/640/480/?image=1024",
                            Description = "Et quia magnam aperiam et. Magnam est et sed quia laborum iusto labore. Ipsam similique adipisci. Aspernatur accusamus et a aut vel quia. Culpa dolores quia dignissimos quam repellendus iure. Magnam nulla quia quisquam aliquam non id.",
                            IsCheckedOut = true,
                            Isbn = "5456745222811",
                            PageCount = 702,
                            PublicationDate = new DateOnly(2023, 3, 16),
                            Publisher = "Purdy, Sauer and Pacocha",
                            Title = "Sit ut doloremque."
                        },
                        new
                        {
                            Id = 11,
                            Author = "Rhianna Beahan",
                            CategoryId = 2,
                            CoverImage = "https://picsum.photos/640/480/?image=338",
                            Description = "Rem ducimus rem nemo necessitatibus magni sapiente labore corporis. Quas ea ipsam. Eos et et sit aut sapiente repellat animi eveniet eum. Ut qui fugiat. Sint tenetur fuga ducimus qui fugit perferendis odit.",
                            IsCheckedOut = false,
                            Isbn = "3732229807883",
                            PageCount = 596,
                            PublicationDate = new DateOnly(2015, 2, 15),
                            Publisher = "Graham, Murray and Anderson",
                            Title = "Aut explicabo temporibus."
                        },
                        new
                        {
                            Id = 12,
                            Author = "Branson Monahan",
                            CategoryId = 6,
                            CoverImage = "https://picsum.photos/640/480/?image=503",
                            Description = "Debitis a eos. Nulla possimus corrupti eos est suscipit maiores nam nihil. Nostrum amet laboriosam officia in non. Unde qui quidem et.",
                            IsCheckedOut = false,
                            Isbn = "4515844444638",
                            PageCount = 448,
                            PublicationDate = new DateOnly(2017, 2, 19),
                            Publisher = "Blick - Lehner",
                            Title = "Ut ut unde."
                        },
                        new
                        {
                            Id = 13,
                            Author = "Trycia Cruickshank",
                            CategoryId = 2,
                            CoverImage = "https://picsum.photos/640/480/?image=750",
                            Description = "Non praesentium recusandae voluptas incidunt tempora omnis. Nostrum velit est tenetur fugiat qui. Qui itaque rem.",
                            IsCheckedOut = false,
                            Isbn = "3806213591017",
                            PageCount = 261,
                            PublicationDate = new DateOnly(2019, 10, 28),
                            Publisher = "Denesik, Walter and Keebler",
                            Title = "Quia pariatur adipisci."
                        },
                        new
                        {
                            Id = 14,
                            Author = "Cheyenne Bogisich",
                            CategoryId = 8,
                            CoverImage = "https://picsum.photos/640/480/?image=437",
                            Description = "Iste dolore explicabo voluptatem quaerat totam. Voluptatem ex quis aperiam totam dolorem. Quam occaecati voluptas sit ad et nihil accusamus qui voluptatem.",
                            IsCheckedOut = true,
                            Isbn = "3477593068262",
                            PageCount = 914,
                            PublicationDate = new DateOnly(2022, 11, 3),
                            Publisher = "Tillman, Kassulke and Zemlak",
                            Title = "Ut eveniet sit."
                        },
                        new
                        {
                            Id = 15,
                            Author = "Rosina Hodkiewicz",
                            CategoryId = 10,
                            CoverImage = "https://picsum.photos/640/480/?image=1048",
                            Description = "Vel qui aut nobis. Quasi eos et officia ab voluptas amet ut eligendi. Iusto aut vero. Esse consequatur laborum ut non ut quos.",
                            IsCheckedOut = true,
                            Isbn = "5557178450885",
                            PageCount = 475,
                            PublicationDate = new DateOnly(2018, 5, 13),
                            Publisher = "Roberts, Deckow and Marvin",
                            Title = "Porro perferendis cumque."
                        },
                        new
                        {
                            Id = 16,
                            Author = "Laurine Zboncak",
                            CategoryId = 9,
                            CoverImage = "https://picsum.photos/640/480/?image=438",
                            Description = "Nesciunt velit rem et quam ea odit ipsum possimus. Voluptatum quo ad a neque deleniti. Alias ratione quo et quos provident quas quia. Magni animi aperiam neque officia qui illum beatae nihil. Odit sint nobis aliquid omnis. Facere cum consequatur quia qui.",
                            IsCheckedOut = false,
                            Isbn = "0966945251580",
                            PageCount = 903,
                            PublicationDate = new DateOnly(2018, 7, 23),
                            Publisher = "D'Amore Group",
                            Title = "Commodi et culpa."
                        },
                        new
                        {
                            Id = 17,
                            Author = "Garfield Schimmel",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=940",
                            Description = "Tenetur animi id at dolores ratione nihil est in. Ullam asperiores quod id nesciunt possimus expedita eos odio. Quia aliquam sit. Eos voluptatum veniam rerum.",
                            IsCheckedOut = true,
                            Isbn = "1398838512284",
                            PageCount = 236,
                            PublicationDate = new DateOnly(2021, 9, 24),
                            Publisher = "Schmeler - Bernier",
                            Title = "Adipisci sed quo."
                        },
                        new
                        {
                            Id = 18,
                            Author = "Darren Hermann",
                            CategoryId = 10,
                            CoverImage = "https://picsum.photos/640/480/?image=164",
                            Description = "Cumque esse in asperiores distinctio et possimus vero. Veritatis tempora porro. Est quo eum nulla nemo aut magnam dolorum.",
                            IsCheckedOut = false,
                            Isbn = "0157034938141",
                            PageCount = 194,
                            PublicationDate = new DateOnly(2023, 4, 9),
                            Publisher = "Streich, Batz and Hane",
                            Title = "Eaque dolor dolor."
                        },
                        new
                        {
                            Id = 19,
                            Author = "Berenice Koelpin",
                            CategoryId = 7,
                            CoverImage = "https://picsum.photos/640/480/?image=515",
                            Description = "Tenetur suscipit molestiae et. Ab unde excepturi quo tenetur suscipit quod pariatur est at. Molestias rerum enim dolor itaque voluptatum. Dolores facilis ratione. Dicta est quibusdam non et sunt impedit magni pariatur quidem.",
                            IsCheckedOut = true,
                            Isbn = "8872827541323",
                            PageCount = 531,
                            PublicationDate = new DateOnly(2020, 8, 8),
                            Publisher = "Harber Group",
                            Title = "Et numquam quasi."
                        },
                        new
                        {
                            Id = 20,
                            Author = "Aric Koepp",
                            CategoryId = 6,
                            CoverImage = "https://picsum.photos/640/480/?image=737",
                            Description = "Voluptatem rem dolorem eos rerum alias eos aperiam occaecati maiores. Perspiciatis quo neque ullam sint. Aspernatur officiis aut ut laudantium porro sed ducimus et perspiciatis. Debitis enim magnam esse similique est voluptas consequatur iste. Incidunt non at. Rerum neque quasi porro rerum ratione quos.",
                            IsCheckedOut = false,
                            Isbn = "7969401278919",
                            PageCount = 388,
                            PublicationDate = new DateOnly(2017, 9, 20),
                            Publisher = "Wuckert, McLaughlin and Stanton",
                            Title = "Autem animi consequatur."
                        },
                        new
                        {
                            Id = 21,
                            Author = "Maia Carter",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=46",
                            Description = "Iste magni qui aut qui aliquid adipisci. Ut dolorem quisquam quae veniam laborum. Quam et facere voluptas consequatur quod molestiae. Id provident dolorem natus. Qui fugit non qui ut.",
                            IsCheckedOut = true,
                            Isbn = "6984020037366",
                            PageCount = 918,
                            PublicationDate = new DateOnly(2014, 9, 13),
                            Publisher = "Skiles Group",
                            Title = "Ea omnis et."
                        },
                        new
                        {
                            Id = 22,
                            Author = "Tyrel Zemlak",
                            CategoryId = 10,
                            CoverImage = "https://picsum.photos/640/480/?image=490",
                            Description = "Autem debitis magnam sequi eveniet doloribus beatae. Esse omnis praesentium voluptatem. Dolor voluptate non sapiente magni deleniti totam temporibus. Unde temporibus quos voluptatem.",
                            IsCheckedOut = true,
                            Isbn = "5480531297905",
                            PageCount = 906,
                            PublicationDate = new DateOnly(2015, 8, 15),
                            Publisher = "Gleichner - Bernier",
                            Title = "Nisi omnis consequuntur."
                        },
                        new
                        {
                            Id = 23,
                            Author = "Rose Cummerata",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=795",
                            Description = "Aut dolor unde voluptas laudantium distinctio debitis. Qui aut nisi accusamus corrupti possimus velit. Quia consequatur est ut non. Doloribus suscipit ut saepe magni et. Eligendi quam et architecto blanditiis. Quo voluptatem possimus aspernatur et veniam.",
                            IsCheckedOut = false,
                            Isbn = "6076458357274",
                            PageCount = 612,
                            PublicationDate = new DateOnly(2023, 2, 14),
                            Publisher = "Shields - MacGyver",
                            Title = "Eius aspernatur recusandae."
                        },
                        new
                        {
                            Id = 24,
                            Author = "Katlynn Kessler",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=565",
                            Description = "Ut corrupti doloribus. Enim repellat nobis voluptatum rerum neque est. Corrupti non repellendus error vitae earum. Tempora voluptatem sapiente sint odit ut. Quia non unde dolor ad quia nisi. Suscipit provident et ipsa quia.",
                            IsCheckedOut = false,
                            Isbn = "3002666058354",
                            PageCount = 892,
                            PublicationDate = new DateOnly(2018, 3, 13),
                            Publisher = "Shields LLC",
                            Title = "Architecto sit possimus."
                        },
                        new
                        {
                            Id = 25,
                            Author = "Timmy Cruickshank",
                            CategoryId = 6,
                            CoverImage = "https://picsum.photos/640/480/?image=321",
                            Description = "Veritatis fugit consectetur magnam omnis eaque id et. Quia autem quis. Qui ducimus sed et non aut nam quasi. Quos doloremque delectus et dignissimos laudantium facilis nobis ut. Maxime repellendus quia delectus consequatur eaque. Quidem officiis amet et iste non minima non perferendis.",
                            IsCheckedOut = true,
                            Isbn = "2612852234953",
                            PageCount = 897,
                            PublicationDate = new DateOnly(2022, 4, 23),
                            Publisher = "Luettgen, Zulauf and Beier",
                            Title = "Maxime officiis voluptatum."
                        },
                        new
                        {
                            Id = 26,
                            Author = "Anthony Konopelski",
                            CategoryId = 7,
                            CoverImage = "https://picsum.photos/640/480/?image=644",
                            Description = "Ad itaque aspernatur nobis quo molestiae dolorem necessitatibus magni ut. Cupiditate sed eaque nisi est. Sit ipsa id ut fugit magni reiciendis id quia. Vel dignissimos tempore non mollitia molestiae nihil perferendis est. Mollitia consequuntur neque. Voluptas quaerat cupiditate.",
                            IsCheckedOut = true,
                            Isbn = "1041918193636",
                            PageCount = 502,
                            PublicationDate = new DateOnly(2023, 2, 11),
                            Publisher = "Paucek Inc",
                            Title = "Deleniti enim aut."
                        },
                        new
                        {
                            Id = 27,
                            Author = "Jesse Bailey",
                            CategoryId = 9,
                            CoverImage = "https://picsum.photos/640/480/?image=152",
                            Description = "Nesciunt necessitatibus aut et rerum vero est. Quisquam rerum provident cum dolor unde. Ipsum labore autem pariatur aut itaque est quod quos placeat. Et omnis eum et amet velit atque beatae delectus neque. Est enim nemo velit quod incidunt placeat.",
                            IsCheckedOut = true,
                            Isbn = "7176513770051",
                            PageCount = 819,
                            PublicationDate = new DateOnly(2018, 7, 31),
                            Publisher = "Orn, Ullrich and Botsford",
                            Title = "Ut voluptas aspernatur."
                        },
                        new
                        {
                            Id = 28,
                            Author = "Kristina Ratke",
                            CategoryId = 2,
                            CoverImage = "https://picsum.photos/640/480/?image=528",
                            Description = "Occaecati perspiciatis nobis velit quam doloribus aliquid. Numquam eveniet praesentium. Veritatis deleniti voluptatem quo. Praesentium perferendis sequi earum sint aliquam. Amet et exercitationem aut.",
                            IsCheckedOut = true,
                            Isbn = "6040106515378",
                            PageCount = 977,
                            PublicationDate = new DateOnly(2021, 5, 24),
                            Publisher = "Hand, Hoeger and Windler",
                            Title = "Suscipit consectetur cumque."
                        },
                        new
                        {
                            Id = 29,
                            Author = "Maybelle Kreiger",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=538",
                            Description = "Quis sed perferendis. Optio perspiciatis qui magnam in beatae enim placeat exercitationem reprehenderit. Doloribus quis at fugit ut aut aspernatur. Et eligendi quia quos aut cumque velit. Corrupti nihil dolor nisi omnis et aut laudantium.",
                            IsCheckedOut = true,
                            Isbn = "9698278330199",
                            PageCount = 231,
                            PublicationDate = new DateOnly(2019, 5, 17),
                            Publisher = "Greenfelder LLC",
                            Title = "Deleniti voluptatem quia."
                        },
                        new
                        {
                            Id = 30,
                            Author = "Kasey Hirthe",
                            CategoryId = 9,
                            CoverImage = "https://picsum.photos/640/480/?image=222",
                            Description = "Ipsa sed quae quasi iste ut iure et dolor. Sint eaque qui impedit rerum similique sequi molestiae. Eum consequuntur consequatur ratione voluptatem error. Consequatur sunt dignissimos excepturi maxime.",
                            IsCheckedOut = true,
                            Isbn = "7744713693571",
                            PageCount = 532,
                            PublicationDate = new DateOnly(2018, 11, 20),
                            Publisher = "Gibson Group",
                            Title = "Autem ab in."
                        },
                        new
                        {
                            Id = 31,
                            Author = "Magdalen Padberg",
                            CategoryId = 3,
                            CoverImage = "https://picsum.photos/640/480/?image=852",
                            Description = "Quas ut praesentium ullam ipsum nam itaque enim non natus. Beatae eligendi quis nihil sapiente quis vel quia autem. Dolorum sapiente modi ea delectus sunt. Ad sed animi ut deserunt voluptatibus minima. Accusantium nesciunt sunt dolores velit ea. Voluptas illum et.",
                            IsCheckedOut = true,
                            Isbn = "4148329253038",
                            PageCount = 962,
                            PublicationDate = new DateOnly(2022, 6, 23),
                            Publisher = "Johns Group",
                            Title = "Quia non sunt."
                        },
                        new
                        {
                            Id = 32,
                            Author = "Demetris Weber",
                            CategoryId = 4,
                            CoverImage = "https://picsum.photos/640/480/?image=1003",
                            Description = "Quo vel sed animi velit ea nihil dolor ipsa. Enim suscipit quia quibusdam. Similique reprehenderit voluptatem temporibus eius commodi.",
                            IsCheckedOut = true,
                            Isbn = "1091094772217",
                            PageCount = 848,
                            PublicationDate = new DateOnly(2016, 6, 4),
                            Publisher = "Hane LLC",
                            Title = "Corrupti quo sunt."
                        },
                        new
                        {
                            Id = 33,
                            Author = "Mohammed Beer",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=427",
                            Description = "Beatae ratione cumque aut ratione asperiores dignissimos repellendus. Quibusdam aut iure dicta perspiciatis. Vitae ipsa minima. At ipsa laborum enim odit. Sapiente voluptatibus suscipit.",
                            IsCheckedOut = false,
                            Isbn = "9208909543777",
                            PageCount = 722,
                            PublicationDate = new DateOnly(2018, 4, 23),
                            Publisher = "Miller, Marks and Daniel",
                            Title = "Doloremque provident odit."
                        },
                        new
                        {
                            Id = 34,
                            Author = "Michel Satterfield",
                            CategoryId = 6,
                            CoverImage = "https://picsum.photos/640/480/?image=992",
                            Description = "Officiis deserunt inventore sit perferendis aut. Exercitationem velit ea numquam laudantium praesentium. Qui reiciendis reprehenderit nisi. Architecto aspernatur est autem voluptas numquam nostrum esse rerum. Voluptatem at qui sapiente dolorum ab nam consequatur cumque maiores.",
                            IsCheckedOut = false,
                            Isbn = "2276003953171",
                            PageCount = 756,
                            PublicationDate = new DateOnly(2015, 5, 29),
                            Publisher = "Ernser - Gutkowski",
                            Title = "Ducimus et ducimus."
                        },
                        new
                        {
                            Id = 35,
                            Author = "Gabriel Beahan",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=92",
                            Description = "Quas voluptas magni sequi ut est ea sint dolores. Rem rerum dolorem recusandae inventore tempore voluptatem quo explicabo atque. Vel quaerat hic et minima minus. Eius consequuntur pariatur aliquam commodi. Omnis reprehenderit est totam fugit consequatur aut aperiam.",
                            IsCheckedOut = true,
                            Isbn = "6015903151265",
                            PageCount = 961,
                            PublicationDate = new DateOnly(2015, 6, 25),
                            Publisher = "Murphy - Volkman",
                            Title = "Est eligendi ducimus."
                        },
                        new
                        {
                            Id = 36,
                            Author = "Curtis Ledner",
                            CategoryId = 10,
                            CoverImage = "https://picsum.photos/640/480/?image=877",
                            Description = "Libero veritatis pariatur quisquam. Rem velit exercitationem est voluptatem tenetur autem optio. Velit repellat ipsam corporis exercitationem corporis expedita.",
                            IsCheckedOut = false,
                            Isbn = "3744378992822",
                            PageCount = 634,
                            PublicationDate = new DateOnly(2020, 5, 21),
                            Publisher = "Davis - Jones",
                            Title = "Optio quis doloremque."
                        },
                        new
                        {
                            Id = 37,
                            Author = "Ettie Hamill",
                            CategoryId = 10,
                            CoverImage = "https://picsum.photos/640/480/?image=911",
                            Description = "Dolores quis porro sint tempora voluptas et. Harum libero ullam enim natus architecto culpa quia et. Dolorum qui animi et porro quas architecto. Laboriosam dolorem alias similique voluptas aut sequi voluptate.",
                            IsCheckedOut = true,
                            Isbn = "3136590824973",
                            PageCount = 729,
                            PublicationDate = new DateOnly(2022, 11, 3),
                            Publisher = "Rippin - Kunze",
                            Title = "Eum consequatur eos."
                        },
                        new
                        {
                            Id = 38,
                            Author = "Cory Spinka",
                            CategoryId = 6,
                            CoverImage = "https://picsum.photos/640/480/?image=338",
                            Description = "Cum vero et dolorem velit nesciunt sequi. Ut qui velit reprehenderit. Dignissimos laudantium sint odit asperiores nesciunt tempore qui. Excepturi laborum et ea quo quas qui. Cupiditate et facilis velit cumque minima aliquam repellendus.",
                            IsCheckedOut = false,
                            Isbn = "3994352680034",
                            PageCount = 507,
                            PublicationDate = new DateOnly(2015, 6, 28),
                            Publisher = "Terry, O'Keefe and Ankunding",
                            Title = "Et aliquam expedita."
                        },
                        new
                        {
                            Id = 39,
                            Author = "Mable Lowe",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=872",
                            Description = "Placeat nostrum quod amet distinctio voluptatem soluta ea autem. Error laborum quasi soluta voluptate quisquam veritatis dolore eos. Ut autem ea animi recusandae.",
                            IsCheckedOut = false,
                            Isbn = "4876722625205",
                            PageCount = 328,
                            PublicationDate = new DateOnly(2022, 4, 3),
                            Publisher = "Leannon and Sons",
                            Title = "Autem dignissimos et."
                        },
                        new
                        {
                            Id = 40,
                            Author = "Gerard Reinger",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=889",
                            Description = "Velit placeat repellendus a non qui. Vero exercitationem neque explicabo similique. Aspernatur assumenda veniam ipsa impedit totam consequatur similique voluptates. Est minus odit et velit quam earum dolores qui. Animi illo sunt alias soluta est aut repellat.",
                            IsCheckedOut = true,
                            Isbn = "9106278590289",
                            PageCount = 168,
                            PublicationDate = new DateOnly(2019, 11, 28),
                            Publisher = "Hintz, Dickens and Kuhn",
                            Title = "Minus eum vitae."
                        },
                        new
                        {
                            Id = 41,
                            Author = "Joey Waters",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=600",
                            Description = "Cum veniam commodi. Ex consequatur placeat reiciendis in et et est et ut. Et blanditiis voluptas vero voluptas.",
                            IsCheckedOut = false,
                            Isbn = "9353652328673",
                            PageCount = 913,
                            PublicationDate = new DateOnly(2015, 1, 12),
                            Publisher = "Turcotte and Sons",
                            Title = "Iusto aliquid doloremque."
                        },
                        new
                        {
                            Id = 42,
                            Author = "Layla Wuckert",
                            CategoryId = 6,
                            CoverImage = "https://picsum.photos/640/480/?image=250",
                            Description = "Qui fugit ducimus sunt sit architecto. Quos error vel voluptates doloribus quia. Consequatur in illo illum est eum labore rerum et.",
                            IsCheckedOut = true,
                            Isbn = "3475121744886",
                            PageCount = 751,
                            PublicationDate = new DateOnly(2024, 3, 13),
                            Publisher = "Jones, Towne and Parisian",
                            Title = "Vitae occaecati culpa."
                        },
                        new
                        {
                            Id = 43,
                            Author = "Baylee Raynor",
                            CategoryId = 10,
                            CoverImage = "https://picsum.photos/640/480/?image=64",
                            Description = "Dolor exercitationem autem non officiis et eius. Omnis sit placeat laudantium doloremque beatae iusto eius minus. Aspernatur ut veniam voluptatem sed unde laboriosam tempora.",
                            IsCheckedOut = true,
                            Isbn = "9051932699726",
                            PageCount = 176,
                            PublicationDate = new DateOnly(2016, 8, 23),
                            Publisher = "Windler - Spencer",
                            Title = "Voluptas facere culpa."
                        },
                        new
                        {
                            Id = 44,
                            Author = "Kailee Stamm",
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/640/480/?image=1078",
                            Description = "Vero et praesentium sunt dolore accusamus est. Facere saepe sint in temporibus omnis sit. Aliquam labore ea dolores ducimus aliquid commodi. Ut laudantium et provident cumque eos molestiae.",
                            IsCheckedOut = true,
                            Isbn = "0755010892861",
                            PageCount = 820,
                            PublicationDate = new DateOnly(2016, 10, 27),
                            Publisher = "Heaney - Bechtelar",
                            Title = "Eligendi ea voluptas."
                        },
                        new
                        {
                            Id = 45,
                            Author = "Chadrick Kuvalis",
                            CategoryId = 8,
                            CoverImage = "https://picsum.photos/640/480/?image=925",
                            Description = "Amet repellendus delectus sed vero et laudantium molestiae ut dignissimos. Magnam quas neque excepturi pariatur eveniet aliquid. Laboriosam voluptas alias neque. Vero eveniet veritatis. Quas error dolorem unde. Dolor ut rerum perspiciatis atque labore unde natus saepe non.",
                            IsCheckedOut = true,
                            Isbn = "6983511692954",
                            PageCount = 400,
                            PublicationDate = new DateOnly(2015, 5, 30),
                            Publisher = "Jones - Gulgowski",
                            Title = "Exercitationem corrupti eos."
                        },
                        new
                        {
                            Id = 46,
                            Author = "Forest Hansen",
                            CategoryId = 4,
                            CoverImage = "https://picsum.photos/640/480/?image=463",
                            Description = "Nemo esse fugit facilis omnis accusamus quasi. Facilis iusto id voluptatem ut. Mollitia ut ut aliquid veritatis porro quia id modi. Asperiores tempora voluptatum cupiditate in.",
                            IsCheckedOut = false,
                            Isbn = "5767213283495",
                            PageCount = 599,
                            PublicationDate = new DateOnly(2022, 5, 2),
                            Publisher = "Wisozk LLC",
                            Title = "Voluptate minima tenetur."
                        },
                        new
                        {
                            Id = 47,
                            Author = "Dillon Little",
                            CategoryId = 8,
                            CoverImage = "https://picsum.photos/640/480/?image=644",
                            Description = "Consectetur quo est omnis qui perspiciatis id numquam. Harum quas magni provident quae quidem. Deserunt vel id perferendis nemo ea molestiae.",
                            IsCheckedOut = true,
                            Isbn = "0719638028552",
                            PageCount = 172,
                            PublicationDate = new DateOnly(2018, 1, 27),
                            Publisher = "Waelchi LLC",
                            Title = "Non porro aut."
                        },
                        new
                        {
                            Id = 48,
                            Author = "Alaina Ruecker",
                            CategoryId = 3,
                            CoverImage = "https://picsum.photos/640/480/?image=1044",
                            Description = "Esse qui earum tempora. Repellendus voluptates illo enim voluptatum eum. Quas quia non. Sequi et nobis voluptas perspiciatis eum.",
                            IsCheckedOut = false,
                            Isbn = "6389356217251",
                            PageCount = 964,
                            PublicationDate = new DateOnly(2014, 11, 22),
                            Publisher = "Kihn Inc",
                            Title = "Quisquam eveniet vero."
                        },
                        new
                        {
                            Id = 49,
                            Author = "Javonte Marvin",
                            CategoryId = 5,
                            CoverImage = "https://picsum.photos/640/480/?image=633",
                            Description = "Dolores cumque sed beatae non id aperiam corrupti et. Quia qui impedit ex non in officiis quod rerum. Tempore ut voluptate tempore odit aut in atque.",
                            IsCheckedOut = false,
                            Isbn = "2678896729077",
                            PageCount = 326,
                            PublicationDate = new DateOnly(2016, 2, 4),
                            Publisher = "Windler LLC",
                            Title = "Eveniet vel quod."
                        },
                        new
                        {
                            Id = 50,
                            Author = "Mylene Murray",
                            CategoryId = 8,
                            CoverImage = "https://picsum.photos/640/480/?image=669",
                            Description = "Voluptatem exercitationem dignissimos. Quisquam accusantium unde ut laborum qui cupiditate voluptatibus ullam sequi. Autem repellat sint maiores. Et reiciendis ducimus.",
                            IsCheckedOut = false,
                            Isbn = "4204293391906",
                            PageCount = 878,
                            PublicationDate = new DateOnly(2019, 4, 26),
                            Publisher = "Luettgen - Wisoky",
                            Title = "Delectus aut et."
                        });
                });

            modelBuilder.Entity("MediaLendingService.Server.Entities.LiteraryCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LiteraryCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beauty, Jewelery & Sports"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Outdoors"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Garden, Music & Beauty"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Clothing & Toys"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Shoes & Shoes"
                        });
                });

            modelBuilder.Entity("MediaLendingService.Server.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8d7e64a-7f5d-4e4e-a071-0fba45e8abc8"),
                            ConcurrencyStamp = "90898a3a-0030-45ca-864c-655368c38764",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = new Guid("ee3d910e-94ae-400b-b529-984520fa9639"),
                            ConcurrencyStamp = "78ddc32f-51be-4500-ac3c-49e7ce5a0c23",
                            Name = "Librarian",
                            NormalizedName = "LIBRARIAN"
                        });
                });

            modelBuilder.Entity("MediaLendingService.Server.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PreferredName");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MediaLendingService.Server.Entities.BookEntity", b =>
                {
                    b.HasOne("MediaLendingService.Server.Entities.LiteraryCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("MediaLendingService.Server.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MediaLendingService.Server.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MediaLendingService.Server.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("MediaLendingService.Server.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaLendingService.Server.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MediaLendingService.Server.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
